branch-defaults:
  master:
    environment: transferbreak-dev
global:
  application_name: transferbreak-ruby
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Passenger Standalone)
  default_region: us-west-1
  profile: eb-cli
  sc: git
